module.exports = {
    en: {
        translation: {
            SKILL_NAME: 'Premium Hello World',
            WELCOME_MSG: 'Welcome to Premium Hello World! You can say hello or ask for what you can buy! How can I help?',
            REPROMPT_MSG: 'I didn\'t catch that. What can I help you with?',
            PRODUCT_OWNED_MSG: 'Good News! You already have the {{productName}}. ',
            YES_NO_QUESTION: [
                'Would you like another greeting?',
                'Can I give you another greeting?',
                'Do you want to hear another greeting?'
            ],
            PRODUCT_LIST_MSG: 'Products available for purchase at this time are {{products}}. To learn more about a product, say, Tell me more about. followed by the product name. If you are ready to buy, say. Buy. followed by the product name. So what can I help you with?',
            NO_PURCHASABLE_PRODUCT_MSG: 'You can\'t buy this product right now. Sorry about that.',
            LEARN_MORE_PROMPT: [
                'I\'ll get more information about the product. Would you wait for me?',
                'I\'ll get you more details about the product. Can you wait for me?',
                'Let me fetch you the details. Can you stand by?',
                'Can you wait a little bit while I get you more details?'
            ],
            SIMPLE_GREETINGS: ['Howdy!', 'Hello!', 'How are you?', 'Hiya!', 'What\'s up?'],
            SIMPLE_GREETING: 'Here\'s your simple greeting. {{greeting}}.',
            SIMPLE_GOODBYES: ['Goodbye!', 'Have a great day!', 'Come back again soon!'],
            SURE_MSG: ['Sure. ', 'No problem. ', 'Ok. '],
            BUY_UNKNOWN_RESULT_MSG: 'Something unexpected happened, but thanks for your interest in the {{productName}}.',
            BUY_ERROR_MSG: 'Sorry, there was an error with in skill purchasing. Please make sure you unblock purchases in the Alexa app and try again.',
            BOUGHT_SOMETHING_MSG: 'You have bought the following products. ',
            BOUGHT_NOTHING_MSG: 'You haven\'t purchased anything yet. To learn more about the products you can buy, try saying. what can I buy. or just say yes to get another greeting.',
            AVAILABLE_CREDITS_MSG: 'You have {{count}} premium goodbye left. ',
            AVAILABLE_CREDITS_MSG_plural: 'You have {{count}} premium goodbyes left. ',
            CREDITS_FOLLOWUP_STOCK: 'Just say stop, and you\'ll use one!',
            CREDITS_FOLLOWUP_NO_STOCK: 'You can buy more by saying. buy goodbyes pack.',
            HELP_MSG: 'You can say hello to me or ask for what you can buy! How can I help?',
            ERROR_MSG: 'Sorry, there was an error. Please try again.',
            SPECIAL_GOODBYE_MSG: 'Here\'s your special goodbye. ',
            SPECIAL_GOODBYE_LANG_MSG: 'That\'s goodbye in {{lang}}',
            SPECIAL_GREETING_MSG: 'Here\'s your special greeting. ',
            SPECIAL_GREETING_LANG_MSG: 'That\'s hello in {{lang}}.',
            AND_MSG: ' and $1',
            UPSELL_ENTITLEMENT_MSG: 'By the way, you can now get greetings in more languages. Are you interested?',
            UPSELL_SUBSCRIPTION_MSG: 'By the way, you can now get greetings with voices in native languages. Are you interested in this service?',
            UPSELL_CONSUMABLE_MSG: 'If you want to hear goodbyes in different languages just say. buy goodbyes pack to get credit. ',
            CANCEL_PRODUCT_ERROR_MSG: 'There was an error handling your product cancellation request. Please try again or contact us for help.',
            'en-US': 'American English',
            'en-AU': 'Australian English',
            'en-GB': 'British English',
            'en-IN': 'Indian English',
            'hi-IN': 'Hindi',
            'de-DE': 'German',
            'es-ES': 'Castilian Spanish',
            'fr-FR': 'French',
            'ja-JP': 'Japanese',
            'it-IT': 'Italian'
        }
    },
    es: {
        translation: {
            SKILL_NAME: 'Hola Mundo Premium',
            WELCOME_MSG: 'Te doy la bienvenida a Hola Mundo Premium! Puedes decir hola o preguntarme que puedes comprar! Cómo te puedo ayudar?',
            REPROMPT_MSG: 'No te he entendido. Cómo te puedo ayudar?',
            PRODUCT_OWNED_MSG: 'Buenas noticias! Ya tienes {{productName}}. ',
            YES_NO_QUESTION: [
                'Quieres otro saludo?',
                'Puedo darte otro saludo?',
                'Quieres oir otro saludo?'
            ],
            PRODUCT_LIST_MSG: 'Los productos que puedes comprar son {{products}}. Para saber más sobre un producto, solo dí. Más información sobre. seguido del nombre del producto. Si ya quieres comprar, solo dí. Comprar. seguido del nombre del producto. Cómo te puedo ayudar?',
            NO_PURCHASABLE_PRODUCT_MSG: 'No puedes comprar este producto. Perdona.',
            LEARN_MORE_PROMPT: [
                'Buscaré más información sobre el producto. Me esperas?',
                'Buscaré más detalles sobre el producto. Me puedes esperar?',
                'Déjame buscar más detalles. Puedes esperarme?',
                'Puedes esperar un momento mientras busco más detalles?'
            ],
            SIMPLE_GREETINGS: ['Qué hay?','Qué tal?', 'Hola!', 'Cómo estás?', 'Como vá?'],
            SIMPLE_GREETING: 'Aquí está tu saludo simple. {{greeting}}.',
            SIMPLE_GOODBYES: ['Adiós!', 'Que tengas un buen día!', 'Vuelve pronto!'],
            SURE_MSG: ['Vale. ', 'Claro. ', 'Ok. '],
            BUY_UNKNOWN_RESULT_MSG: 'Ha ocurrido algo raro, pero gracias por tu interés en {{productName}}.',
            BUY_ERROR_MSG: 'Perdona, ha habido un error con las compras in skill. Asegúrate de que no estás bloqueando las compras en tu app Alexa.',
            BOUGHT_SOMETHING_MSG: 'Has comprado los siguientes productos. ',
            BOUGHT_NOTHING_MSG: 'No has comprado nada aun. Si quieres saber que puedes comprar sólo dí. que puedo comprar. o sólo dí sí para obtener otro saludo.',
            AVAILABLE_CREDITS_MSG: 'Te queda {{count}} despedida premium. ',
            AVAILABLE_CREDITS_MSG_plural: 'Te quedan {{count}} despedidas premium. ',
            CREDITS_FOLLOWUP_STOCK: 'Sólo di para, y gastarás una!',
            CREDITS_FOLLOWUP_NO_STOCK: 'Puedes comprar más diciendo. comprar paquete de despedidas.',
            HELP_MSG: 'Puedes decirme hola y preguntarme por lo que puedes comprar. Como te puedo ayudar?',
            ERROR_MSG: 'Perdona, ha ocurrido un error. Por favor inténtalo otra vez.',
            SPECIAL_GOODBYE_MSG: 'Aquí está tu despedida especial. ',
            SPECIAL_GOODBYE_LANG_MSG: 'Significa adiós en {{lang}}',
            SPECIAL_GREETING_MSG: 'Aquí está tu bienvenida especial. ',
            SPECIAL_GREETING_LANG_MSG: 'Significa hola en {{lang}}.',
            AND_MSG: ' y $1',
            UPSELL_ENTITLEMENT_MSG: 'Por cierto, ahora puedes obtener saludos en otros idiomas. Te interesa?',
            UPSELL_SUBSCRIPTION_MSG: 'Por cierto, ahora puedes obtener los saludos con voces nativas. Te interesa conocer este servicio?',
            UPSELL_CONSUMABLE_MSG: 'Si quieres escuchar despedidas en otros idiomas solo dí. compra paquete de despedidas para obtener crédito. ',
            CANCEL_PRODUCT_ERROR_MSG: 'Hubo un error procesando la cancelación del producto. Por favor inténtalo otra vez o contáctanos para obtener ayuda.',
            'en-US': 'Inglés Americano',
            'en-AU': 'Inglés Australiano',
            'en-GB': 'Inglés Británico',
            'en-IN': 'Inglés de la India',
            'hi-IN': 'Hindi',
            'de-DE': 'Alemán',
            'es-ES': 'Castellano',
            'fr-FR': 'Francés',
            'ja-JP': 'Japonés',
            'it-IT': 'Italiano'
        }
    },
    it: {
        translation: {
            SKILL_NAME: 'Ciao Mondo Premium',
            WELCOME_MSG: 'Benvenuti a Ciao Mondo Premium! Puoi dirmi Ciao oppure chiedermi cosa puoi comprare! Cosa vuoi fare?',
            REPROMPT_MSG: 'Non ho capito. Come posso aiutarti?',
            PRODUCT_OWNED_MSG: 'Ottima notizia! Possiedi già {{productName}}. ',
            YES_NO_QUESTION: [
                'Vuoi un altro saluto?',
                'Posso offrirti un altro saluto?',
                'Vuoi sentire un altro saluto?'
            ],
            PRODUCT_LIST_MSG: 'I prodotti che puoi ascquistare sono {{products}}. Per sapere di più di un prodotto, chiedimi: dammi più informazioni riguardo a, seguito dal nome del prodotto. Se desideri acquistarlo, basta dire, compra, e il nome del prodotto. Come posso aiutarti?',
            NO_PURCHASABLE_PRODUCT_MSG: 'Non hai prodotti da poter acquistare.',
            LEARN_MORE_PROMPT: [
                'Troverò maggiori informazioni sul prodotto. Mi aspetteresti?',
                'Ti fornirò maggiori dettagli sul prodotto. Puoi aspettarmi?',
                'Lascia che ti prenda i dettagli. Puoi aspettare?',
                'Puoi aspettare un po \'mentre ti ottengo maggiori dettagli?'
            ],
            SIMPLE_GREETINGS: ['Come va?', 'Come stai?', 'Ciao!', 'Tutto bene?'],
            SIMPLE_GREETING: 'Ecco il tuo saluto semplice. {{greeting}}.',
            SIMPLE_GOODBYES: ['Arrivederci!', 'Buona giornata!', 'A presto!'],
            SURE_MSG: ['Cerro. ', 'non c\'è problema. ', 'Ok. '],
            BUY_UNKNOWN_RESULT_MSG: 'È successo qualcosa di inaspettato, ma grazie per esserti interessato di {{productName}}.',
            BUY_ERROR_MSG: 'Scusami, ma è successo un error con l\'acquisto. Assicurati di avere i permessi necessari per gli acquisti vocali. Queste impostazioni si trovano nella tua app Alexa.',
            BOUGHT_SOMETHING_MSG: 'Hai comprato i seguenti prodotti. ',
            BOUGHT_NOTHING_MSG: 'Non hai ancora comprato nulla. Se vuoi sapere cosa puoi comprare prova a chiedere "cosa posso comprare?". Oppure dì di sì per un altro saluto.',
            AVAILABLE_CREDITS_MSG: 'Hai ancora {{count}} addio premium rimasto. ',
            AVAILABLE_CREDITS_MSG_plural: 'Hai ancora {{count}} addii premium rimasti. ',
            CREDITS_FOLLOWUP_STOCK: 'Dì stop, e ne userai uno!',
            CREDITS_FOLLOWUP_NO_STOCK: 'Puoi comprarne altri dicendo. compra pacchetto di addii.',
            HELP_MSG: 'Puoi dirmi Ciao oppure chiedermi cosa puoi comprare! Cosa vuoi fare?',
            ERROR_MSG: 'Si è verificato un errore. Per favore riprova!',
            SPECIAL_GOODBYE_MSG: 'Ecco il tuo addio speciale. ',
            SPECIAL_GOODBYE_LANG_MSG: 'Vuol dire addio in {{lang}}',
            SPECIAL_GREETING_MSG: 'Ecco il tuo saluto speciale. ',
            SPECIAL_GREETING_LANG_MSG: 'Significa ciao in {{lang}}.',
            AND_MSG: ' e $1',
            UPSELL_ENTITLEMENT_MSG: 'Tra l\'altro, puoi avere saluti in altre lingue! sei interessato?',
            UPSELL_SUBSCRIPTION_MSG: 'A proposito, ora puoi ricevere il tuo saluto con le voci nelle lingue native. Sei interessato a questo servizio?',
            UPSELL_CONSUMABLE_MSG: 'Se vuoi sentire il tuo addio in un\'altra lingua, dì semplicemente, voglio acquistare il Pacchetto di addii, per ottenere credito',
            CANCEL_PRODUCT_ERROR_MSG: 'Si è verificato un errore. Por favore riprova di nuovo o contatta il servizio clienti per ricevere aiuto.',
            'en-US': 'Inglese Americano',
            'en-AU': 'Inglese Australiano',
            'en-GB': 'Inglese Britannico',
            'en-IN': 'Inglese Indiano',
            'hi-IN': 'Hindi',
            'de-DE': 'Tedesco',
            'es-ES': 'Spagnolo',
            'fr-FR': 'Francese',
            'ja-JP': 'Giappone',
            'it-IT': 'Italiano'
        }
    },
    'es-US': {
        translation: {
            SURE_MSG: 'Okey.'
        }
    },
    fr: {
        translation: {
            SKILL_NAME: `Genie des Salutations Premium`,
            WELCOME_MSG: `Bienvenue chez le Génie des Salutations version Premium! Je peux vous dire bonjour ou bien vous proposez les produits disponibles à l'achat. Quel est votre choix?`,
            REPROMPT_MSG: `Désolé, je n'ai pas bien compris. Souhaitez-vous entendre une autre salutation?`,
            PRODUCT_OWNED_MSG: `Bonne nouvelle! Vous avez déjà acheté {{productName}}. `,
            YES_NO_QUESTION: [
                `Voulez-vous entendre une autre salutation?`,
                `Souhaitez-vous écouter un autre message d'accueil?`
            ],
            PRODUCT_LIST_MSG: `Les produits actuellement disponibles à l'achat sont {{products}}. Pour en savoir plus sur un produit, dites-moi par exemple 'donne-moi plus d'informations sur l'abonnement premium'. Pour acheter un produit, dites-moi par exemple 'achètes l'abonnement premium'. Souhaitez-vous entendre une autre salutation?`,
            NO_PURCHASABLE_PRODUCT_MSG: `Il n'y a plus de produits disponibles à l'achat.`,
            LEARN_MORE_PROMPT: [
                'I\'ll get more information about the product. Would you wait for me?',
                'Je vous obtiendrai plus de détails sur le produit. Peux-tu m\'attendre?',
                'Laissez-moi vous chercher les détails. Peux-tu m\'attendre?',
                'Pouvez-vous attendre un peu pendant que je vous obtienne plus de détails?'
            ],
            SIMPLE_GREETINGS: ['Bonjour!', 'Enchantée!', 'Comment allez-vous', 'Waza!'],
            SIMPLE_GREETING: `Voici votre message d'accueil. {{greeting}}.`,
            SIMPLE_GOODBYES: ['Au revoir!', 'A bientôt!', 'A très vite!'],
            SURE_MSG: ['Bien sûr. ', 'Je t\'en prie. ', 'Bien. '],
            BUY_UNKNOWN_RESULT_MSG: `Désolé, un problème inattendu est survenu pendant votre achat. Merci de votre intérêt pour le produit {{productName}}`,
            BUY_ERROR_MSG: `Désolé, il y a un problème avec votre achat. Assurez-vous d'avoir activer les achats vocaux depuis l'application Alexa avant de réessayer.`,
            BOUGHT_SOMETHING_MSG: `Vous avez acheté les produits suivants. `,
            BOUGHT_NOTHING_MSG: `Vous n'avez pas encore acheté de produits. Pour connaitre les produits disponibles, il suffit de me dire 'que puis-je acheter'. Souhaitez-vous entendre une autre salutation?`,
            AVAILABLE_CREDITS_MSG: `Il vous reste {{count}} adieu personnalisé.`,
            CREDITS_FOLLOWUP_STOCK: `Dites simplement 'stop' and vous utiliserez un credit.`,
            CREDITS_FOLLOWUP_NO_STOCK: `Pour acheter des credits supplémentaires, dites simplement 'achètes le pack d'aurevoir personnalisé'.`,
            HELP_MSG: `Je peux vous dire bonjour ou bien vous proposez les produits disponibles à l'achat. Quel est votre choix?`,
            ERROR_MSG: `Désolé, je n'ai pas compris. Pouvez-vous reformuler?`,
            SPECIAL_GOODBYE_MSG: `Voici votre adieux personalisé: `,
            SPECIAL_GOODBYE_LANG_MSG: `Cela veut dire 'au revoir' en {{lang}}.`,
            SPECIAL_GREETING_MSG: `Voici votre message d'accueil personnalisé. `,
            SPECIAL_GREETING_LANG_MSG: `Cela veut dire 'bonjour' en {{lang}}.`,
            AND_MSG: ' et $1',
            UPSELL_ENTITLEMENT_MSG: `Vous pouvez maintenant obtenir des messages d'accueil dans plusieurs langues. ça t'intéresse?`,
            UPSELL_SUBSCRIPTION_MSG: 'Soit dit en passant, vous pouvez maintenant recevoir des messages d\'accueil avec des voix dans les langues maternelles. Êtes-vous intéressé par ce service?',
            UPSELL_CONSUMABLE_MSG: 'Je veux entendre des adieux dans différentes langues juste dire, achètes Pack des Adieux Personnalisés, pour obtenir du crédit. ',
            CANCEL_PRODUCT_ERROR_MSG: `Il y a eu un problème pendant l'annulation de votre achat. Veuillez ressayer ou bien contacter notre équipe support pour obtenir plus d'aide.`,
            'en-US': 'Anglais Américain',
            'en-AU': 'Anglais Australian',
            'en-GB': 'Anglais Britannique',
            'en-IN': 'Anglais Indien',
            'hi-IN': 'Hindi',
            'de-DE': 'Allemand',
            'es-ES': 'Castillan',
            'fr-FR': 'Français',
            'ja-JP': 'Japonais',
            'it-IT': 'Italien'
        }
    }
}
